{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Convertin to Solids",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\n\r\nimport clr\r\nimport System\r\nfrom System.Collections.Generic import *\r\n\r\nfrom itertools import repeat\r\n\r\npf_path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.ProgramFilesX86)\r\nimport sys\r\nsys.path.append('%s\\IronPython 2.7\\Lib' %pf_path)\r\nimport traceback\r\nimport random\r\nimport string\r\n\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\nfrom Autodesk.DesignScript.Geometry import Point as DynPoint\r\nfrom Autodesk.DesignScript.Geometry import Line as DynLine\r\nfrom Autodesk.DesignScript.Geometry import Curve as DynCurve\r\n\r\nclr.AddReference('RevitServices')\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nfrom Autodesk.Revit.DB.Structure import StructuralType\r\n\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\ndef tolist(obj1):\r\n\tif hasattr(obj1,'__iter__'): return obj1\r\n\telse: return [obj1]\r\n\r\ndef flatten(x):\r\n    result = []\r\n    try:\r\n    \tfor el in x:\r\n        \tif hasattr(el, \"__iter__\") and not isinstance(el, basestring):\r\n        \t    result.extend(flatten(el))\r\n        \telse:\r\n        \t    result.append(el)\r\n    except:\r\n    \tresult = x\r\n    return result\r\n\r\ngeom = UnwrapElement(IN[0])\r\nif geom != None:\r\n\tgeom = tolist(geom)\r\nelse:\r\n\tpass\r\n\r\ntemp_path = System.IO.Path.GetTempPath()\r\nsatOpt = SATExportOptions()\r\nopt1 = Options()\r\nopt1.ComputeReferences = True\r\n\r\n#Find a 3D view type\r\ncollector1 = FilteredElementCollector(doc)\r\nviewFamilyTypes = collector1.OfClass((ViewFamilyType))\r\nfor e in viewFamilyTypes:\r\n\tif str(e.ViewFamily) == \"ThreeDimensional\":\r\n\t\tviewType = e.Id\r\n\t\tbreak\r\n\r\ndef NewForm_background(s1):\r\n\ttry:\r\n\t\trandomname = ''.join([random.choice(string.ascii_letters + string.digits) for n in xrange(5)])\r\n\t\tTransactionManager.Instance.EnsureInTransaction(doc)\r\n\t\tsat_path = '%s%s.sat' % (temp_path, randomname)\r\n\t\tstatus = True\r\n\t\tfinalres = []\r\n\t\tresultgeom = []\r\n\t\tthreedeeview = View3D.CreateIsometric(doc, viewType)\r\n\t\tthreedeeviewid = threedeeview.Id\r\n\t\tkilist = List[ElementId]([threedeeviewid])\r\n\t\ttid = []\r\n\t\tfor each in s1:\r\n\t\t\ttid.append(each.Id)\r\n\t\tielements = List[ElementId](tid)\r\n\t\tthreedeeview.IsolateElementsTemporary(ielements)\r\n\t\tcollectorinside = FilteredElementCollector(doc,threedeeviewid).ToElements()\r\n\t\telemento = []\r\n\t\tfor k in collectorinside:\r\n\t\t\telemento.append(int(str(k.Id)))\r\n\t\tfor each in s1:\r\n\t\t\tif int(str(each.Id)) in elemento:\r\n\t\t\t\tdoc.Export(temp_path, randomname, kilist, satOpt)\r\n\t\t\t\teachlist = Geometry.ImportFromSAT(sat_path)\r\n\t\t\t\ttmplist = []\r\n\t\t\t\tfor e in eachlist:\r\n\t\t\t\t\ttmplist.append(e)\r\n\t\t\t\tresultgeom.append(tmplist)\r\n\t\t\t\tSystem.IO.File.Delete(sat_path)\r\n\t\t\telse:\r\n\t\t\t\tresultgeom = [None]\r\n\t\t\tbreak\r\n\t\tdoc.Delete(threedeeview.Id)\r\n\t\tfinalres.append(flatten(resultgeom))\r\n\t\tTransactionManager.Instance.TransactionTaskDone()\r\n\t\treturn finalres\r\n\texcept:\r\n\t\treturn traceback.format_exc(),''\r\n\r\nresult = NewForm_background(geom)\r\nOUT = flatten(result)\r\nsatOpt.Dispose()\r\nopt1.Dispose()",
      "VariableInputPorts": true,
      "Id": "f53fa20d6e434023a15932b2d73710ec",
      "Inputs": [
        {
          "Id": "deefc8cedd024ec7905eea0c99b7154a",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3926e661981e45df8ebaed32ed6dc40b",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementsSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [],
      "Id": "481f102e2cb447d9ae6413faafe74f69",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3b3845e7578e48499a2077eab4cd4875",
          "Name": "Elements",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Scale@double,double,double",
      "Id": "82b0a331be6c429b9da89bb62786a0a5",
      "Inputs": [
        {
          "Id": "54b54dbbad704f63935a104d4362629c",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "17a17a5f7eb3484c8d767dd3089301ed",
          "Name": "xamount",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5145d577a5b44d288af656e02b0fcd5b",
          "Name": "yamount",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "15dde5d908054820aca8ae8bd78dc7d8",
          "Name": "zamount",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9ec857b1aa734742a5f031bd3a3eec75",
          "Name": "Geometry",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Scale non-uniformly around the origin\n\nGeometry.Scale (xamount: double = 1, yamount: double = 1, zamount: double = 1): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1000;",
      "Id": "40c2e117b6de4ff687c3844c4efb8509",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "112f6ba1192740268d116c81fce11be6",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "3926e661981e45df8ebaed32ed6dc40b",
      "End": "54b54dbbad704f63935a104d4362629c",
      "Id": "83443094cd194b2183e3c501ca810467"
    },
    {
      "Start": "3b3845e7578e48499a2077eab4cd4875",
      "End": "deefc8cedd024ec7905eea0c99b7154a",
      "Id": "92e9fcd87ea940bf88ce1505e7279202"
    },
    {
      "Start": "112f6ba1192740268d116c81fce11be6",
      "End": "17a17a5f7eb3484c8d767dd3089301ed",
      "Id": "371124d754ed477f98314c24ed6a0fd6"
    },
    {
      "Start": "112f6ba1192740268d116c81fce11be6",
      "End": "5145d577a5b44d288af656e02b0fcd5b",
      "Id": "d26ac0f623df43889361c42ea4e6e28b"
    },
    {
      "Start": "112f6ba1192740268d116c81fce11be6",
      "End": "15dde5d908054820aca8ae8bd78dc7d8",
      "Id": "597071a357ff4ff78783b5eb2e4ff5f3"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.5.0.7460",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "f53fa20d6e434023a15932b2d73710ec",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 572.172413410242,
        "Y": 367.11035746201856
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Elements",
        "Id": "481f102e2cb447d9ae6413faafe74f69",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 261.29589632829368,
        "Y": 372.80172786177104
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Scale",
        "Id": "82b0a331be6c429b9da89bb62786a0a5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 841.39564145910254,
        "Y": 365.28701559454265
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "40c2e117b6de4ff687c3844c4efb8509",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 566.0,
        "Y": 458.0
      }
    ],
    "Annotations": [],
    "X": 74.987710373245136,
    "Y": 32.280067430426584,
    "Zoom": 0.82269535937499993
  }
}